---
name: gassy
version: '0.0.0'
github: "tylerjl/gassy"
license: MIT
author: "Tyler Langlois"
maintainer: "Tyler Langlois"

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

executables:
  gassy:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - aeson
    - base
    - blaze-html
    - bloodhound
    - http-api-data
    - http-client
    - lens
    - lens-aeson
    - magicbane
    - rio
    - scientific
    - servant-blaze
    - time
    - vector
    - wai-extra
    - wai-middleware-static
    default-extensions:
    - DataKinds
    - DeriveAnyClass
    - DeriveGeneric
    - NoImplicitPrelude
    - OverloadedStrings
    - ScopedTypeVariables
    - TypeOperators
    - UnicodeSyntax
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
