name: gassy
version: '0.0.0'
github: "tylerjl/gassy"
license: MIT
author: "Tyler Langlois"
maintainer: "Tyler Langlois"

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

executables:
  gassy:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - aeson
    - base
    - blaze-html
    - bloodhound
    - classy-prelude
    - http-client
    - lens
    - lens-aeson
    - mtl
    - simple-logger
    - Spock
    - time
    - vector
    - wai-middleware-static
    default-extensions:
    - NoImplicitPrelude
    - OverloadedStrings
    - ScopedTypeVariables
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
