---
resolver: lts-13.3
packages:
- .
extra-deps:
- bloodhound-0.16.0.0
- containers-0.5.11.0
- ekg-json-0.1.0.6
- ekg-wai-0.1.0.3
- magicbane-0.4.0
- monad-metrics-0.2.1.2
- wai-middleware-metrics-0.2.4
